### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data problem in allennlp prediction

### ISSUE THREAD

**Issue by sajastu** [sebastianGehrmann/bottom-up-summary#14]
Hey,

I'd like to train content-selector on my dataset. After training with allennlp with the specified options, I tried to run prediction on test set which I generated using `preprocess_copy.py` to transform into a new format. Then, I run the prediction command:

`CUDA_VISIBLE_DEVICES=0,1 python -m allennlp.run predict  models/model.tar.gz data/multicopy.test.src.txt --output out/prediction.txt --cuda-device 1 --batch-size 10`

But the odds are not in my favor, and the prediction ends up with this error message after prediction:

> Traceback (most recent call last):
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 21, in <module>
>     run()
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
>     main(prog="allennlp")
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
>     args.func(args)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 200, in _predict
>     manager.run()
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 179, in run
>     for batch_json in lazy_groups_of(self._get_json_data(), self._batch_size):
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/util.py", line 105, in <lambda>
>     return iter(lambda: list(islice(iterator, 0, group_size)), [])
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/predict.py", line 162, in _get_json_data
>     yield self._predictor.load_line(line)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 45, in load_line
>     return json.loads(line)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/home/sajad/anaconda3/envs/allennlp/lib/python3.6/json/decoder.py", line 342, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
> 2019-03-30 15:44:53,390 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpmdt8z2s3

Any idea to fix this?

**Comment by sebastianGehrmann** [comment]
This looks like your text might include symbols that break the json parser. Could you try removing them?

**Comment by sajastu** [comment]
@sebastianGehrmann I, actually, don't think so since I chose a single sample from the validation set (which prediction was performed on in the training time), but it ends up with the exact same error. 

In addition, `multicopy.test.src.txt` is a bunch of lines, each containing some 0's and 1's, right? Do we need to have some sort of JSONs (like [here](https://github.com/allenai/allennlp/issues/1095)) to pass to allennlp predict?

**Comment by sajastu** [comment]
Finally, the problem solved! I should have run `multicopy.test.pred.txt` instead of `multicopy.test.src.txt`!
