### ISSUE TITLE
Extremely Lower R-LCS

### ISSUE THREAD

**Issue by fajri91** [sebastianGehrmann/bottom-up-summary#16]
Hi, I evaluated the given output with the pyrouge package by first removing the `<t>` and `</t>`.
The complete result is:

ROUGE-1:
rouge_1_f_score: 0.4153 with confidence interval (0.4131, 0.4176)
rouge_1_recall: 0.4261 with confidence interval (0.4234, 0.4289)
rouge_1_precision: 0.4317 with confidence interval (0.4293, 0.4343)

ROUGE-2:
rouge_2_f_score: 0.1877 with confidence interval (0.1855, 0.1899)
rouge_2_recall: 0.1929 with confidence interval (0.1905, 0.1952)
rouge_2_precision: 0.1953 with confidence interval (0.1929, 0.1977)

ROUGE-l:
rouge_l_f_score: 0.2792 with confidence interval (0.2772, 0.2813)
rouge_l_recall: 0.2872 with confidence interval (0.2848, 0.2896)
rouge_l_precision: 0.2897 with confidence interval (0.2875, 0.2920)

R-1 and R-2 seem similar to the paper, but why ROUGE-LCS is pretty low?

**Comment by sebastianGehrmann** [comment]
Are you sure your cleaning is correct or you calling pyrouge with the correct params? I have not seen this error before, even from people who used pyrouge to replicate.

**Comment by fajri91** [comment]
I am using
- Summary: bottom_up_cnndm_015_threshold.out
- Reference: in cnndm_shuffled_test.zip 

And I have manually checked the cleansing. 
eg. (from reference)
**before cleansing:**
`<t>` vatanka : tensions between iran and saudi arabia are at an unprecedented level . `</t>` `<t>` iran has proposed a four-point plan for yemen but saudis have ignored it . `</t>` `<t>` vatanka : saudis have tried to muster a ground invasion coalition but have failed . `</t>`
**after cleansing** -- _all in 1 line, put each to a file_
vatanka : tensions between iran and saudi arabia are at an unprecedented level . iran has proposed a four-point plan for yemen but saudis have ignored it . vatanka : saudis have tried to muster a ground invasion coalition but have failed .

I am quite sure there s nothing wrong with the Pyrouge as I use the evaluation code from pointer-generator paper. I get the same result with See et al and other exp. Is there any specific configuration of Pyrouge that might be different?

**Comment by sebastianGehrmann** [comment]
I am not sure since I am not using pyrouge directly. Other people had no problems replicating the numbers with pyrouge, so I am not sure what you are doing wrong. Can you check that you get my numbers following my pyrouge wrapper script?

**Comment by fseasy** [comment]
I have some experience for LCS-too-low. Every sentence should be joint with `\n`, because ROUEG use so-called union-LCS. don't put many sentence in one line.
