### ISSUE TITLE
Preprocessing step using OPENNMT-py gives 0 features? 

### ISSUE THREAD

**Issue by muzaluisa** [sebastianGehrmann/bottom-up-summary#4]
Hi, 

My professor Filip G. has talked to you on EMNLP and he told me that I should try this paper results (telling that it is easy to repeat the procedure). I got stuck on the 1st step somehow. Would be glad, if you can help me here.

So, so suggested in the 1st step in http://opennmt.net/OpenNMT-py/Summarization.html, I do preprocessing (same command line for preprocessing CNNDM dataset)

Then I get 0 number of features: 

[2018-11-08 13:25:06,615 INFO] Extracting features...
[2018-11-08 13:25:06,676 INFO]  * number of source features: 0.
[2018-11-08 13:25:06,676 INFO]  * number of target features: 0.
[2018-11-08 13:25:06,676 INFO] Building `Fields` object...
[2018-11-08 13:25:06,676 INFO] Building & saving training data...

While training is finished, I receive an error, saying that Vocabulary size is 0.

How should I approach the problem and make sure that I do not get 0 features?

**Comment by sebastianGehrmann** [comment]
Hm that should not happen. Can you open an issue in the main OpenNMT-py repository? 
Please include the exact command you ran.
